version: '2'
services:
  composer:
    image: prooph/composer:7.1
    volumes:
      - .:/app
    links:
      - postgres:postgres
      - mariadb:mariadb
      - mysql:mysql

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=event_store_tests

  mariadb:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=event_store_tests

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=event_store_tests

  sqlsvr:
    image: microsoft/mssql-server-windows-express
    environment:
      - sa_password=
      - ACCEPT_EULA=
      - attach_dbs="[{'dbName':'event_store_tests'}]"